version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./_docker/config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: project_app

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./_docker/config/mysql/conf.d:/etc/mysql/conf.d
      - ./_docker/tmp/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8886:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    container_name: project_db

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MEMORY=128
    container_name: project_memcached

  elasticsearch:
    image: elasticsearch:8.10.3
    volumes:
      # - './_docker/config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
      - ./_docker/tmp/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "elastic"
      discovery.type: single-node
      xpack.security.enabled: false
    ports:
      - "9200:9200"
    container_name: project_elasticsearch

#  adminer:
#    image: adminer:latest
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    container_name: project_adminer

#  phpmyadmin:
#    image: phpmyadmin:latest
#    restart: always
#    ports:
#      - "8090:80"
#    environment:
#      - PMA_ARBITRARY=1
#    depends_on:
#      - db
#    container_name: project_phpmyadmin
